# Gradle projects to build for the corresponding Minecraft version.
["1.21.11"]
projects = ["common", "fabric", "neoforge"]

["1.20.6"]
projects = ["common", "fabric", "neoforge"]

["1.19.4"]
projects = ["common", "fabric", "forge"]

["1.18.2"]
projects = ["common", "fabric", "forge"]
