[versions]
kotlin = "2.2.20"
stonecutter = "0.8.3"
fabric-loom = "1.14-SNAPSHOT"
moddev = "2.0.140"
fletchingtable = "0.1.0-alpha.22"
foojay-resolver = "1.0.0"
tomlkt = "0.6.0"
mapping-io = "0.8.0"
modpublisher = "2.1.7+snapshot.0"
jetbrains-changelog = "2.2.0"
serialization-json = "1.10.0"

[libraries]
mapping-io = { group = "net.fabricmc", name = "mapping-io", version.ref = "mapping-io"}
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-json" }
kotlin-serialization-toml = { group = "dev.eav.tomlkt", name = "tomlkt", version.ref = "tomlkt" }

[plugins]
stonecutter = { id = "dev.kikugie.stonecutter", version.ref = "stonecutter" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
moddev-legacy = {id = "net.neoforged.moddev.legacyforge", version.ref = "moddev"}
fletchingtable = { id = "dev.kikugie.fletching-table", version.ref = "fletchingtable" }
fletchingtable-fabric = { id = "dev.kikugie.fletching-table.fabric", version.ref = "fletchingtable" }
fletchingtable-neoforge = { id = "dev.kikugie.fletching-table.neoforge", version.ref = "fletchingtable" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }
jetbrains-changelog = { id = "org.jetbrains.changelog", version.ref = "jetbrains-changelog" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }