[versions]
modpublisher = "2.1.7+snapshot.0"
shadow = "8.3.6"
jetbrains-changelog = "2.2.0"

[plugins]
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jetbrains-changelog = { id = "org.jetbrains.changelog", version.ref = "jetbrains-changelog" }