modLoader = "javafml"
loaderVersion = "${neoforgeLoaderReq}"
issueTrackerURL = "${modIssues}"
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
displayURL = "${modHomepage}"
logoFile = "icon.png"
logoBlur = true
authors = "${modAuthors}"
description = '''
${modDescription}
'''

[[mixins]]
config = "freecam-common.mixins.json"

[[mixins]]
config = "freecam-neoforge.mixins.json"

[[dependencies.${modId}]]
modId = "neoforge"
versionRange = "${neoforgeReq}"
type = "required"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "minecraft"
versionRange = "${neoforgeMcReq}"
type = "required"
ordering = "NONE"
side = "CLIENT"
